version: '3.7'

services:

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: julencio@julencio.com
      PGADMIN_DEFAULT_PASSWORD: julencio
    ports:
      - "90:80"
    volumes:
      - pgadmin_data_:/var/lib/pgadmin

volumes:
    pgadmin_data_:
